name: Test action

on:
  issues:
    types: [created, opened]
  pull_request:
    types: [created, opened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
